#!/usr/bin/env bash
# ============================================================================
#  JARVIS (MARK XXXIX) — "always there" installer for Linux (Mint/Ubuntu/Debian)
#
#  Makes JARVIS start automatically on login (no need to run it by hand) and
#  adds a `jarvis` command you can run anytime. Once running it lives in the
#  system tray — closing the window keeps it alive in the background.
#
#  Usage:
#     bash scripts/install_autostart.sh              # install (XDG autostart)
#     bash scripts/install_autostart.sh --service    # also a systemd --user unit
#     bash scripts/install_autostart.sh --uninstall  # remove everything
# ============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
APP_NAME="jarvis"

if [ -x "$PROJECT_DIR/venv/bin/python" ]; then
  PYBIN="$PROJECT_DIR/venv/bin/python"
elif [ -x "$PROJECT_DIR/venv/bin/python3" ]; then
  PYBIN="$PROJECT_DIR/venv/bin/python3"
else
  PYBIN="$(command -v python3 || true)"
fi
[ -n "$PYBIN" ] || { echo "❌ python3 not found. Run setup-linux.sh first."; exit 1; }

BIN_DIR="$HOME/.local/bin"
AUTOSTART_DIR="$HOME/.config/autostart"
APPS_DIR="$HOME/.local/share/applications"
SYS_DIR="$HOME/.config/systemd/user"
ICON="$PROJECT_DIR/face.png"
LAUNCHER="$BIN_DIR/$APP_NAME"

uninstall() {
  echo "==> Removing JARVIS autostart + launchers"
  rm -f "$AUTOSTART_DIR/$APP_NAME.desktop" "$APPS_DIR/$APP_NAME.desktop" "$LAUNCHER"
  systemctl --user disable --now "$APP_NAME.service" 2>/dev/null || true
  rm -f "$SYS_DIR/$APP_NAME.service"
  echo "✅ Uninstalled. Your project files are untouched."
}

[ "${1:-}" = "--uninstall" ] && { uninstall; exit 0; }

echo "==> Project: $PROJECT_DIR"
echo "==> Python : $PYBIN"
mkdir -p "$BIN_DIR" "$AUTOSTART_DIR" "$APPS_DIR"

# 1) Command-line launcher: `jarvis`
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# JARVIS launcher (auto-generated by install_autostart.sh)
cd "$PROJECT_DIR"
if [ -f "$PROJECT_DIR/venv/bin/activate" ]; then
  # shellcheck disable=SC1091
  source "$PROJECT_DIR/venv/bin/activate"
fi
exec "$PYBIN" main.py
EOF
chmod +x "$LAUNCHER"

# 2) .desktop entry — used for BOTH the app menu and login autostart
write_desktop() {
  cat > "$1" <<EOF
[Desktop Entry]
Type=Application
Name=J.A.R.V.I.S
Comment=Always-on personal AI assistant
Exec=$LAUNCHER
Icon=$ICON
Terminal=false
Categories=Utility;Assistant;
StartupNotify=false
X-GNOME-Autostart-enabled=true
X-GNOME-Autostart-Delay=8
EOF
}
write_desktop "$APPS_DIR/$APP_NAME.desktop"
write_desktop "$AUTOSTART_DIR/$APP_NAME.desktop"

echo "✅ Installed."
echo "   • Command    : $LAUNCHER   (type 'jarvis' any time)"
echo "   • App menu   : $APPS_DIR/$APP_NAME.desktop"
echo "   • Auto-start : $AUTOSTART_DIR/$APP_NAME.desktop  (runs on next login)"

# 3) Optional: systemd --user unit (auto-restart if it ever crashes)
if [ "${1:-}" = "--service" ]; then
  mkdir -p "$SYS_DIR"
  cat > "$SYS_DIR/$APP_NAME.service" <<EOF
[Unit]
Description=J.A.R.V.I.S assistant
After=graphical-session.target
PartOf=graphical-session.target

[Service]
Type=simple
ExecStart=$LAUNCHER
Restart=on-failure
RestartSec=3

[Install]
WantedBy=graphical-session.target
EOF
  systemctl --user daemon-reload
  systemctl --user enable --now "$APP_NAME.service" || \
    echo "⚠️  systemd enable failed (non-fatal) — XDG autostart still active."
  echo "   • systemd    : $SYS_DIR/$APP_NAME.service (enabled, auto-restarts)"
fi

cat <<'EOF'

Next steps:
  • Start now        :  ~/.local/bin/jarvis
  • On next login    :  it launches by itself
  • It minimises to the system tray — closing the window keeps JARVIS running.
  • Remove later     :  bash scripts/install_autostart.sh --uninstall
EOF
